/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.henriklyra.reseptipankki;

import java.awt.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Henkka
 */
public class Paanakyma extends JFrame {

    private Reseptikortisto rKortisto;
    private ArrayList<Resepti> reseptilista;
    private JButton reseptinappi;
   

    /**
     * Creates new form Paanakyma
     */
    public Paanakyma() {
        initComponents();
        rKortisto = new Reseptikortisto();
        this.rKortisto.tallesta();
        this.alkulistaus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luoResepti = new javax.swing.JDialog();
        otsake1 = new javax.swing.JLabel();
        nimiKentta1 = new javax.swing.JTextField();
        rAineKentta1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        rNimi1 = new javax.swing.JLabel();
        rRAineet1 = new javax.swing.JLabel();
        rvVaiheet1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        taustapaneeli = new javax.swing.JPanel();
        ylapaneeli = new javax.swing.JPanel();
        hakulaatikko = new javax.swing.JTextField();
        nimihakuNappi = new javax.swing.JButton();
        tekstihakuNappi = new javax.swing.JButton();
        lisaaReseptiNappi = new javax.swing.JButton();
        alapaneeli = new javax.swing.JPanel();

        luoResepti.setPreferredSize(new java.awt.Dimension(700, 500));

        otsake1.setText("Luodaan uusi resepti");

        nimiKentta1.setColumns(Resepti.NIMI_PITUUS);
        nimiKentta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimiKentta1ActionPerformed(evt);
            }
        });

        rAineKentta1.setColumns(2);

        jTextField4.setColumns(2);

        rNimi1.setText("Reseptin nimi:");

        rRAineet1.setText("Raaka-aineita:");

        rvVaiheet1.setText("Valmistusvaiheita:");

        jButton2.setText("Luo uusi resepti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout luoReseptiLayout = new javax.swing.GroupLayout(luoResepti.getContentPane());
        luoResepti.getContentPane().setLayout(luoReseptiLayout);
        luoReseptiLayout.setHorizontalGroup(
            luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luoReseptiLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rNimi1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rRAineet1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rvVaiheet1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otsake1)
                    .addComponent(rAineKentta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2)
                        .addComponent(nimiKentta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        luoReseptiLayout.setVerticalGroup(
            luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luoReseptiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(otsake1)
                .addGap(31, 31, 31)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nimiKentta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNimi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rAineKentta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rRAineet1))
                .addGap(47, 47, 47)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rvVaiheet1))
                .addGap(21, 21, 21)
                .addComponent(jButton2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        jScrollPane.setAlignmentX(0);
        jScrollPane.setAlignmentY(0);

        hakulaatikko.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hakulaatikko.setPreferredSize(new java.awt.Dimension(200, 30));
        hakulaatikko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakulaatikkoActionPerformed(evt);
            }
        });
        ylapaneeli.add(hakulaatikko);

        nimihakuNappi.setText("Hae nimestä");
        nimihakuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimihakuNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(nimihakuNappi);

        tekstihakuNappi.setText("Kokotekstihaku");
        tekstihakuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstihakuNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(tekstihakuNappi);

        lisaaReseptiNappi.setBackground(new java.awt.Color(255, 51, 51));
        lisaaReseptiNappi.setText("Lisää resepti");
        lisaaReseptiNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaReseptiNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(lisaaReseptiNappi);

        alapaneeli.setBackground(new java.awt.Color(255, 255, 255));
        alapaneeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout alapaneeliLayout = new javax.swing.GroupLayout(alapaneeli);
        alapaneeli.setLayout(alapaneeliLayout);
        alapaneeliLayout.setHorizontalGroup(
            alapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
        );
        alapaneeliLayout.setVerticalGroup(
            alapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout taustapaneeliLayout = new javax.swing.GroupLayout(taustapaneeli);
        taustapaneeli.setLayout(taustapaneeliLayout);
        taustapaneeliLayout.setHorizontalGroup(
            taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alapaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ylapaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        taustapaneeliLayout.setVerticalGroup(
            taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taustapaneeliLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(alapaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(421, 421, 421))
            .addGroup(taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(taustapaneeliLayout.createSequentialGroup()
                    .addComponent(ylapaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 581, Short.MAX_VALUE)))
        );

        jScrollPane.setViewportView(taustapaneeli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstihakuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstihakuNappiActionPerformed
        this.hakuKaikesta();
    }//GEN-LAST:event_tekstihakuNappiActionPerformed

    private void nimihakuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimihakuNappiActionPerformed
        this.hakuNimesta();
    }//GEN-LAST:event_nimihakuNappiActionPerformed

    private void hakulaatikkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakulaatikkoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hakulaatikkoActionPerformed

    private void lisaaReseptiNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaReseptiNappiActionPerformed
        this.luoResepti.setVisible(true);
    }//GEN-LAST:event_lisaaReseptiNappiActionPerformed

    private void nimiKentta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimiKentta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimiKentta1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Paanakyma().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alapaneeli;
    private javax.swing.JTextField hakulaatikko;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton lisaaReseptiNappi;
    private javax.swing.JDialog luoResepti;
    private javax.swing.JTextField nimiKentta;
    private javax.swing.JTextField nimiKentta1;
    private javax.swing.JButton nimihakuNappi;
    private javax.swing.JLabel otsake;
    private javax.swing.JLabel otsake1;
    private javax.swing.JTextField rAineKentta;
    private javax.swing.JTextField rAineKentta1;
    private javax.swing.JLabel rNimi;
    private javax.swing.JLabel rNimi1;
    private javax.swing.JLabel rRAineet;
    private javax.swing.JLabel rRAineet1;
    private javax.swing.JLabel rvVaiheet;
    private javax.swing.JLabel rvVaiheet1;
    private javax.swing.JPanel taustapaneeli;
    private javax.swing.JButton tekstihakuNappi;
    private javax.swing.JPanel ylapaneeli;
    // End of variables declaration//GEN-END:variables

    public void alkulistaus() {
       this.reseptilistaus(this.rKortisto.tuoKortisto());
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
        
    }

    public void hakuNimesta() {
        this.reseptilistaus(this.rKortisto.nimiHaku(this.hakulaatikko.getText()));
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
    }

    public void hakuKaikesta() {
        this.reseptilistaus(this.rKortisto.taysiHaku(this.hakulaatikko.getText()));
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
    }
        public void reseptilistaus(ArrayList<Resepti> reseptilista) {
        this.alapaneeli.removeAll();
        this.reseptilista = reseptilista;
        this.alapaneeli.setLayout(new GridLayout(this.reseptilista.size(), 1));
        for (int i = 0; i < this.reseptilista.size(); i++) {
            this.alapaneeli.add(this.luoReseptinappi(this.reseptilista.get(i)));
        }
        this.alapaneeli.repaint();
    }
        
            public JButton luoReseptinappi(Resepti uusiResepti) {       
        Resepti resepti;
        resepti = uusiResepti;
        this.reseptinappi = new JButton();
        reseptinappi.setLayout(new GridLayout(2, 1));
        reseptinappi.setSize(400, 100);
        JLabel rNimi = new JLabel();
        rNimi.setFont(new Font("Serif", Font.BOLD, 20));
        rNimi.setSize(100, 20);
        rNimi.setText(resepti.getNimi());
        JTextArea kuvailu = new JTextArea(4, 70);
        kuvailu.setFont(new Font("Serif", Font.BOLD, 12));
        kuvailu.setLineWrap(true);
        kuvailu.setWrapStyleWord(true);
        kuvailu.setEditable(false);
        kuvailu.setText(resepti.getKuvailu());
        reseptinappi.add(rNimi);
        reseptinappi.add(kuvailu);
        this.reseptinappi.addActionListener(e -> new Reseptinakyma(resepti));       
        return this.reseptinappi;       
    }

}
