/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.henriklyra.reseptipankki;

import java.awt.*;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Henkka
 */
public class Paanakyma extends JFrame {

    Reseptikortisto rKortisto;
    Ohjuri kliittyma;

    /**
     * Creates new form Paanakyma
     */
    public Paanakyma() {
        initComponents();
        rKortisto = new Reseptikortisto();
        this.rKortisto.tallesta();
        kliittyma = new Ohjuri();
        this.alkulistaus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        taustapaneeli = new javax.swing.JPanel();
        ylapaneeli = new javax.swing.JPanel();
        hakulaatikko = new javax.swing.JTextField();
        nimihakuNappi = new javax.swing.JButton();
        tekstihakuNappi = new javax.swing.JButton();
        lisaaReseptiNappi = new javax.swing.JButton();
        alapaneeli = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        jScrollPane.setAlignmentX(0);
        jScrollPane.setAlignmentY(0);

        hakulaatikko.setPreferredSize(new java.awt.Dimension(200, 30));
        hakulaatikko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakulaatikkoActionPerformed(evt);
            }
        });
        ylapaneeli.add(hakulaatikko);

        nimihakuNappi.setText("Hae nimestä");
        nimihakuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimihakuNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(nimihakuNappi);

        tekstihakuNappi.setText("Kokotekstihaku");
        tekstihakuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstihakuNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(tekstihakuNappi);

        lisaaReseptiNappi.setBackground(new java.awt.Color(255, 51, 51));
        lisaaReseptiNappi.setText("Lisää resepti");
        ylapaneeli.add(lisaaReseptiNappi);

        alapaneeli.setBackground(new java.awt.Color(255, 255, 255));
        alapaneeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout alapaneeliLayout = new javax.swing.GroupLayout(alapaneeli);
        alapaneeli.setLayout(alapaneeliLayout);
        alapaneeliLayout.setHorizontalGroup(
            alapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
        );
        alapaneeliLayout.setVerticalGroup(
            alapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout taustapaneeliLayout = new javax.swing.GroupLayout(taustapaneeli);
        taustapaneeli.setLayout(taustapaneeliLayout);
        taustapaneeliLayout.setHorizontalGroup(
            taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alapaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ylapaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        taustapaneeliLayout.setVerticalGroup(
            taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taustapaneeliLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(alapaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(taustapaneeliLayout.createSequentialGroup()
                    .addComponent(ylapaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 560, Short.MAX_VALUE)))
        );

        jScrollPane.setViewportView(taustapaneeli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstihakuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstihakuNappiActionPerformed
        this.hakuKaikesta();
    }//GEN-LAST:event_tekstihakuNappiActionPerformed

    private void nimihakuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimihakuNappiActionPerformed
        this.hakuNimesta();
    }//GEN-LAST:event_nimihakuNappiActionPerformed

    private void hakulaatikkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakulaatikkoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hakulaatikkoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Paanakyma().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alapaneeli;
    private javax.swing.JTextField hakulaatikko;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton lisaaReseptiNappi;
    private javax.swing.JButton nimihakuNappi;
    private javax.swing.JPanel taustapaneeli;
    private javax.swing.JButton tekstihakuNappi;
    private javax.swing.JPanel ylapaneeli;
    // End of variables declaration//GEN-END:variables

    public void alkulistaus() {
        kliittyma.reseptilistaus(alapaneeli, this.rKortisto.tuoKortisto());
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
        
    }

    public void hakuNimesta() {
        kliittyma.reseptilistaus(alapaneeli, this.rKortisto.nimiHaku(this.hakulaatikko.getText()));
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
    }

    public void hakuKaikesta() {
        kliittyma.reseptilistaus(alapaneeli, this.rKortisto.taysiHaku(this.hakulaatikko.getText()));
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
    }

}
