
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.henriklyra.reseptipankki;

import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.border.Border;

/**
 * Käyttöliittymäluokka joka toteuttaa reseptien alkulistauksen sekä erilaiset
 * hakulistaukset. Lisäksi luokka toteuttaa näkymän uuden reseptin lisäämiseksi.
 * @author Henkka
 */
public class Paanakyma extends JFrame {
    
    protected static Color taustavari = new Color(242,242,218);
    private Reseptikortisto rKortisto;
    private Resepti resepti;
    private ArrayList<Resepti> reseptilista;
    private JButton reseptinappi;
    private Reseptinakyma rNakyma;
   

    /**
     * Creates new form Paanakyma
     */
    public Paanakyma() {
        initComponents();
        rKortisto = new Reseptikortisto();
        this.rKortisto.tallesta();
        this.alkulistaus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        luoResepti = new javax.swing.JDialog();
        otsake1 = new javax.swing.JLabel();
        rNimiKentta = new javax.swing.JTextField();
        rNimiKentta.setDocument(new JTextFieldLimit(Resepti.NIMI_PITUUS));
        rAineita = new javax.swing.JTextField();
        rAineita.setDocument(new JTextFieldLimit(2));
        vVaiheita = new javax.swing.JTextField();
        vVaiheita.setDocument(new JTextFieldLimit(2));
        rNimi1 = new javax.swing.JLabel();
        rRAineet1 = new javax.swing.JLabel();
        rvVaiheet1 = new javax.swing.JLabel();
        uusiResepti = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        taustapaneeli = new javax.swing.JPanel();
        ylapaneeli = new javax.swing.JPanel();
        hakulaatikko = new javax.swing.JTextField();
        nimihakuNappi = new javax.swing.JButton();
        tekstihakuNappi = new javax.swing.JButton();
        alkulistaus = new javax.swing.JButton();
        lisaaReseptiNappi = new javax.swing.JButton();
        alapaneeli = new javax.swing.JPanel();

        luoResepti.setFocusTraversalPolicyProvider(true);
        luoResepti.setSize(new java.awt.Dimension(800, 300));

        otsake1.setText("Luodaan uusi resepti");

        rNimiKentta.setColumns(Resepti.NIMI_PITUUS);
        rNimiKentta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rNimiKenttaActionPerformed(evt);
            }
        });

        rAineita.setColumns(2);
        rAineita.setText("0");
        rAineita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAineitaActionPerformed(evt);
            }
        });

        vVaiheita.setColumns(2);
        vVaiheita.setText("0");
        vVaiheita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vVaiheitaActionPerformed(evt);
            }
        });

        rNimi1.setText("Reseptin nimi:");

        rRAineet1.setText("Raaka-aineita:");

        rvVaiheet1.setText("Valmistusvaiheita:");

        uusiResepti.setText("Luo uusi resepti");
        uusiResepti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uusiReseptiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout luoReseptiLayout = new javax.swing.GroupLayout(luoResepti.getContentPane());
        luoResepti.getContentPane().setLayout(luoReseptiLayout);
        luoReseptiLayout.setHorizontalGroup(
            luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luoReseptiLayout.createSequentialGroup()
                .addGap(0, 329, Short.MAX_VALUE)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rNimi1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rRAineet1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rvVaiheet1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otsake1)
                    .addComponent(rAineita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vVaiheita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(uusiResepti)
                        .addComponent(rNimiKentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82))
        );
        luoReseptiLayout.setVerticalGroup(
            luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(luoReseptiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(otsake1)
                .addGap(31, 31, 31)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNimiKentta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNimi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rAineita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rRAineet1))
                .addGap(47, 47, 47)
                .addGroup(luoReseptiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vVaiheita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rvVaiheet1))
                .addGap(21, 21, 21)
                .addComponent(uusiResepti)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 500));

        jScrollPane.setBackground(taustavari);
        jScrollPane.setAlignmentX(0);
        jScrollPane.setAlignmentY(0);

        taustapaneeli.setBackground(taustavari);

        ylapaneeli.setBackground(taustavari);

        hakulaatikko.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hakulaatikko.setPreferredSize(new java.awt.Dimension(200, 30));
        hakulaatikko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hakulaatikkoActionPerformed(evt);
            }
        });
        ylapaneeli.add(hakulaatikko);

        nimihakuNappi.setText("Hae nimestä");
        nimihakuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimihakuNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(nimihakuNappi);

        tekstihakuNappi.setText("Kokotekstihaku");
        tekstihakuNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekstihakuNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(tekstihakuNappi);

        alkulistaus.setText("Alkulistaus");
        alkulistaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alkulistausActionPerformed(evt);
            }
        });
        ylapaneeli.add(alkulistaus);

        lisaaReseptiNappi.setBackground(new java.awt.Color(255, 51, 51));
        lisaaReseptiNappi.setText("Lisää resepti");
        lisaaReseptiNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaReseptiNappiActionPerformed(evt);
            }
        });
        ylapaneeli.add(lisaaReseptiNappi);

        alapaneeli.setBackground(taustavari);
        alapaneeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout alapaneeliLayout = new javax.swing.GroupLayout(alapaneeli);
        alapaneeli.setLayout(alapaneeliLayout);
        alapaneeliLayout.setHorizontalGroup(
            alapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1272, Short.MAX_VALUE)
        );
        alapaneeliLayout.setVerticalGroup(
            alapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout taustapaneeliLayout = new javax.swing.GroupLayout(taustapaneeli);
        taustapaneeli.setLayout(taustapaneeliLayout);
        taustapaneeliLayout.setHorizontalGroup(
            taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(alapaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ylapaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        taustapaneeliLayout.setVerticalGroup(
            taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taustapaneeliLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(alapaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(421, 421, 421))
            .addGroup(taustapaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(taustapaneeliLayout.createSequentialGroup()
                    .addComponent(ylapaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 581, Short.MAX_VALUE)))
        );

        jScrollPane.setViewportView(taustapaneeli);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tekstihakuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekstihakuNappiActionPerformed
        this.hakuKaikesta();
    }//GEN-LAST:event_tekstihakuNappiActionPerformed

    private void nimihakuNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimihakuNappiActionPerformed
        this.hakuNimesta();
    }//GEN-LAST:event_nimihakuNappiActionPerformed

    private void hakulaatikkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hakulaatikkoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hakulaatikkoActionPerformed

    private void lisaaReseptiNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaReseptiNappiActionPerformed
        this.luoResepti.setVisible(true);
    }//GEN-LAST:event_lisaaReseptiNappiActionPerformed

    private void rNimiKenttaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rNimiKenttaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rNimiKenttaActionPerformed

    private void uusiReseptiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uusiReseptiActionPerformed
        if (this.rNimiKentta.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Reseptillä täytyy olla nimi!");
        }
        else {
            try {
                int apuri = 0;
                this.resepti = new Resepti(this.rNimiKentta.getText());
                if (this.rAineita.getText().isEmpty() == false && Integer.parseInt(this.rAineita.getText()) > 0) {
                    if (Integer.parseInt(this.rAineita.getText()) > 10) {
                        apuri = 10;
                        JOptionPane.showMessageDialog(null, "Kymmenen raaka-ainetta riittänee");
                    } else {
                        apuri = Integer.parseInt(this.rAineita.getText());
                    }
                        for (int i = 0; i < apuri; i++) {
                            this.resepti.lisaaRaakaAine(new RaakaAine());                        
                    }
                }
                if (this.vVaiheita.getText().isEmpty() == false && Integer.parseInt(this.vVaiheita.getText()) > 0) {
                    if (Integer.parseInt(this.vVaiheita.getText()) > 10) {
                        apuri = 10;
                        JOptionPane.showMessageDialog(null, "Kymmenen valmistusvaihetta riittänee");
                    } else {
                        apuri = Integer.parseInt(this.vVaiheita.getText());
                    }
                    for (int i = 0; i < apuri; i++) {
                        this.resepti.lisaaVaihe("");
                    }
                }
            this.rKortisto.lisaaResepti(this.resepti);
            this.rNakyma = new Reseptinakyma(this, this.rKortisto, this.resepti);
            this.rNakyma.muokkaaReseptia();
            this.rNimiKentta.setText("");
            this.rAineita.setText("0");
            this.vVaiheita.setText("0");          
            this.rKortisto.tallenna();
            this.luoResepti.setVisible(false);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Raaka-aineiden ja valmistusvaiheiden määräksi vain kokonaisluvut");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Odottamaton virhe. Reseptiä ei lisätty");
        }        // TODO add your handling code here:
        }
    }//GEN-LAST:event_uusiReseptiActionPerformed

    private void vVaiheitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vVaiheitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vVaiheitaActionPerformed

    private void alkulistausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alkulistausActionPerformed
        this.alkulistaus();
    }//GEN-LAST:event_alkulistausActionPerformed

    private void rAineitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAineitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rAineitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paanakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Paanakyma().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alapaneeli;
    private javax.swing.JButton alkulistaus;
    private javax.swing.JTextField hakulaatikko;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton lisaaReseptiNappi;
    private javax.swing.JDialog luoResepti;
    private javax.swing.JButton nimihakuNappi;
    private javax.swing.JLabel otsake1;
    private javax.swing.JTextField rAineita;
    private javax.swing.JLabel rNimi1;
    private javax.swing.JTextField rNimiKentta;
    private javax.swing.JLabel rRAineet1;
    private javax.swing.JLabel rvVaiheet1;
    private javax.swing.JPanel taustapaneeli;
    private javax.swing.JButton tekstihakuNappi;
    private javax.swing.JButton uusiResepti;
    private javax.swing.JTextField vVaiheita;
    private javax.swing.JPanel ylapaneeli;
    // End of variables declaration//GEN-END:variables

    public void alkulistaus() {
        this.rKortisto.jarjesta();
       this.reseptilistaus(this.rKortisto.tuoKortisto());
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);        
    }
    
    public void hakuNimesta() {
        this.rKortisto.jarjesta();
        this.reseptilistaus(this.rKortisto.nimiHaku(this.hakulaatikko.getText()));
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
    }

    public void hakuKaikesta() {  
        this.rKortisto.jarjesta();
        this.reseptilistaus(this.rKortisto.taysiHaku(this.hakulaatikko.getText()));
        SwingUtilities.updateComponentTreeUI(this);
        this.jScrollPane.getVerticalScrollBar().setValue(0);
    }
    
    public void reseptilistaus(ArrayList<Resepti> reseptilista) {
        this.alapaneeli.removeAll();
        this.reseptilista = reseptilista;
        
        if (this.reseptilista.size() == 0) {
            JLabel hakutulos = new JLabel();
            hakutulos.setFont(new Font("Serif", Font.BOLD, 20));
            hakutulos.setSize(500, 50);
            hakutulos.setText("Antamallasi hakusanalla ei löytynyt yhtään reseptiä");
            this.alapaneeli.add(hakutulos);
        } else {            
            this.alapaneeli.setLayout(new GridLayout(this.reseptilista.size(), 1));
            for (int i = 0; i < this.reseptilista.size(); i++) {
                this.alapaneeli.add(this.luoReseptinappi(this.reseptilista.get(i)));
            }
        }
        this.alapaneeli.repaint();
    }

    public JButton luoReseptinappi(Resepti uusiResepti) {     
        Resepti resepti;
        resepti = uusiResepti;
        this.reseptinappi = new JButton();
        this.reseptinappi.setLayout(new GridLayout(2, 1));
        this.reseptinappi.setSize(400, 100);
        JLabel rNimi = new JLabel();
        rNimi.setFont(new Font("Serif", Font.BOLD, 20));
        rNimi.setSize(100, 20);
        rNimi.setText(resepti.getNimi());
        JTextArea kuvailu = new JTextArea(4, 70);
        kuvailu.setFont(new Font("Serif", Font.BOLD, 12));
        kuvailu.setBackground(taustavari);
        kuvailu.setOpaque(false);
        kuvailu.setLineWrap(true);       
        kuvailu.setWrapStyleWord(true);
        kuvailu.setEditable(false);
        
        
        
        kuvailu.setText(resepti.getKuvailu());
        this.reseptinappi.add(rNimi);
        this.reseptinappi.add(kuvailu);
        this.reseptinappi.addActionListener(e -> new Reseptinakyma(this, rKortisto, resepti)); 
        this.reseptinappi.setBackground(taustavari);
        this.reseptinappi.setOpaque(true);
        this.reseptinappi.setBorderPainted(false);
        return this.reseptinappi;       
    }

}
