/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.henriklyra.reseptipankki;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

/**
 * Käyttöliittymäluokka joka tuottaa reseptin selailu- ja muokkausnäkymän
 * @author Henkka
 * @see Resepti
 */
public class Reseptinakyma extends javax.swing.JFrame {
    
    private Paanakyma pNakyma;
    private Reseptikortisto rKortisto;
    private Resepti resepti, muokattavaResepti;
    private RaakaAine raakaAine;
    private JPanel otsikkoYla, otsikkoAla, raakaAineetYla, raakaAineetAla, yksiRAine, valmistusvaiheetYla, valmistusvaiheetAla, yksivaihe;
    private JLabel nimi, rAineet, vVaiheet, rAine, mitta, maara;
    private JTextArea kuvailu, vaihe;
    private JTextField nimiMuokkaus, rAineNimiMuokkaus, rAineMittaMuokkaus, rAineMaaraMuokkaus;
    private JButton muokkaaNappi, lisaaRaakaAine, lisaaValmistusvaihe, tallenna, poista;
    private Font leipateksti, otsikkoTeksti;
    

    /**
     * Creates new form Reseptinakyma
     */
    public Reseptinakyma(Paanakyma pNakyma, Reseptikortisto rKortisto, Resepti resepti) {
        this.pNakyma = pNakyma;
        this.rKortisto = rKortisto;
        this.resepti = resepti;
        raakaAine = new RaakaAine();
        this.leipateksti = new Font("Serif", Font.BOLD, 20);
        this.otsikkoTeksti = new Font("Serif", Font.BOLD, 30);
        initComponents();
        this.setVisible(true);
        this.reseptiselailu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tallennuskysely = new javax.swing.JDialog();
        tallennaJaSulje = new javax.swing.JButton();
        suljeTallentamatta = new javax.swing.JButton();
        tallennetaanko = new javax.swing.JLabel();
        reseptinPoistoKysely = new javax.swing.JDialog();
        rPoistetaanNappi = new javax.swing.JButton();
        rEiPoistetaNappi = new javax.swing.JButton();
        rPoistetaanKyselyOtsikko = new javax.swing.JLabel();
        ikkuna = new javax.swing.JScrollPane();
        tausta = new javax.swing.JPanel();
        otsikko = new javax.swing.JPanel();
        raakaAinePaneeli = new javax.swing.JPanel();
        valmVaihePaneeli = new javax.swing.JPanel();

        tallennuskysely.setSize(new java.awt.Dimension(500, 300));

        tallennaJaSulje.setText("Tallenna ja sulje");
        tallennaJaSulje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallennaJaSuljeActionPerformed(evt);
            }
        });

        suljeTallentamatta.setText("Sulje tallentamatta");
        suljeTallentamatta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suljeTallentamattaActionPerformed(evt);
            }
        });

        tallennetaanko.setText("Tallennetaanko resepti ennen sulkemista?");

        javax.swing.GroupLayout tallennuskyselyLayout = new javax.swing.GroupLayout(tallennuskysely.getContentPane());
        tallennuskysely.getContentPane().setLayout(tallennuskyselyLayout);
        tallennuskyselyLayout.setHorizontalGroup(
            tallennuskyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tallennuskyselyLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(tallennuskyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tallennetaanko)
                    .addGroup(tallennuskyselyLayout.createSequentialGroup()
                        .addComponent(suljeTallentamatta)
                        .addGap(96, 96, 96)
                        .addComponent(tallennaJaSulje)))
                .addGap(53, 53, 53))
        );
        tallennuskyselyLayout.setVerticalGroup(
            tallennuskyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tallennuskyselyLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(tallennetaanko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(tallennuskyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tallennaJaSulje)
                    .addComponent(suljeTallentamatta))
                .addGap(59, 59, 59))
        );

        reseptinPoistoKysely.setSize(new java.awt.Dimension(500, 300));

        rPoistetaanNappi.setText("Kyllä, poista resepti");
        rPoistetaanNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rPoistetaanNappiActionPerformed(evt);
            }
        });

        rEiPoistetaNappi.setText("Ei, peruuta toimenpide");
        rEiPoistetaNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEiPoistetaNappiActionPerformed(evt);
            }
        });

        rPoistetaanKyselyOtsikko.setText("Haluatko varmasti poistaa reseptin?");

        javax.swing.GroupLayout reseptinPoistoKyselyLayout = new javax.swing.GroupLayout(reseptinPoistoKysely.getContentPane());
        reseptinPoistoKysely.getContentPane().setLayout(reseptinPoistoKyselyLayout);
        reseptinPoistoKyselyLayout.setHorizontalGroup(
            reseptinPoistoKyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reseptinPoistoKyselyLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(reseptinPoistoKyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rPoistetaanKyselyOtsikko)
                    .addGroup(reseptinPoistoKyselyLayout.createSequentialGroup()
                        .addComponent(rPoistetaanNappi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rEiPoistetaNappi)))
                .addGap(73, 73, 73))
        );
        reseptinPoistoKyselyLayout.setVerticalGroup(
            reseptinPoistoKyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reseptinPoistoKyselyLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(rPoistetaanKyselyOtsikko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(reseptinPoistoKyselyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rPoistetaanNappi)
                    .addComponent(rEiPoistetaNappi))
                .addGap(59, 59, 59))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout otsikkoLayout = new javax.swing.GroupLayout(otsikko);
        otsikko.setLayout(otsikkoLayout);
        otsikkoLayout.setHorizontalGroup(
            otsikkoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        otsikkoLayout.setVerticalGroup(
            otsikkoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout raakaAinePaneeliLayout = new javax.swing.GroupLayout(raakaAinePaneeli);
        raakaAinePaneeli.setLayout(raakaAinePaneeliLayout);
        raakaAinePaneeliLayout.setHorizontalGroup(
            raakaAinePaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        raakaAinePaneeliLayout.setVerticalGroup(
            raakaAinePaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout valmVaihePaneeliLayout = new javax.swing.GroupLayout(valmVaihePaneeli);
        valmVaihePaneeli.setLayout(valmVaihePaneeliLayout);
        valmVaihePaneeliLayout.setHorizontalGroup(
            valmVaihePaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        valmVaihePaneeliLayout.setVerticalGroup(
            valmVaihePaneeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout taustaLayout = new javax.swing.GroupLayout(tausta);
        tausta.setLayout(taustaLayout);
        taustaLayout.setHorizontalGroup(
            taustaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(otsikko, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(raakaAinePaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(valmVaihePaneeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        taustaLayout.setVerticalGroup(
            taustaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taustaLayout.createSequentialGroup()
                .addComponent(otsikko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(raakaAinePaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(valmVaihePaneeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        ikkuna.setViewportView(tausta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ikkuna)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ikkuna)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tallennaJaSuljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallennaJaSuljeActionPerformed
        if (muokattavaResepti.getNimi().trim().isEmpty())
                    JOptionPane.showMessageDialog(null, "Reseptillä täytyy olla nimi!");
                else {
            this.muokattavaResepti.puhdistaResepti();
        this.resepti.kopioi(this.muokattavaResepti);
        this.rKortisto.tallenna();
        this.pNakyma.alkulistaus();
        this.dispose();
        tallennuskysely.setVisible(false);
        }
    }//GEN-LAST:event_tallennaJaSuljeActionPerformed

    private void suljeTallentamattaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suljeTallentamattaActionPerformed
        this.dispose();
        tallennuskysely.setVisible(false);
    }//GEN-LAST:event_suljeTallentamattaActionPerformed

    private void rEiPoistetaNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEiPoistetaNappiActionPerformed
        reseptinPoistoKysely.setVisible(false);
    }//GEN-LAST:event_rEiPoistetaNappiActionPerformed

    private void rPoistetaanNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rPoistetaanNappiActionPerformed
         this.rKortisto.poistaResepti(this.resepti);
        this.rKortisto.tallenna();
        this.pNakyma.alkulistaus();
        this.dispose();
        reseptinPoistoKysely.setVisible(false);
        
    }//GEN-LAST:event_rPoistetaanNappiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reseptinakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reseptinakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reseptinakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reseptinakyma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ikkuna;
    private javax.swing.JPanel otsikko;
    private javax.swing.JButton rEiPoistetaNappi;
    private javax.swing.JLabel rPoistetaanKyselyOtsikko;
    private javax.swing.JButton rPoistetaanNappi;
    private javax.swing.JPanel raakaAinePaneeli;
    private javax.swing.JDialog reseptinPoistoKysely;
    private javax.swing.JButton suljeTallentamatta;
    private javax.swing.JButton tallennaJaSulje;
    private javax.swing.JLabel tallennetaanko;
    private javax.swing.JDialog tallennuskysely;
    private javax.swing.JPanel tausta;
    private javax.swing.JPanel valmVaihePaneeli;
    // End of variables declaration//GEN-END:variables

    public void reseptiselailu() {
        this.otsikkoSelailu();
        this.raakaAineSelailu();
        this.valmistusvaiheSelailu();
        SwingUtilities.updateComponentTreeUI(this);
        this.ikkuna.getVerticalScrollBar().setValue(0);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void muokkaaReseptia() {
        this.muokattavaResepti = new Resepti();
        this.muokattavaResepti.kopioi(this.resepti);
        this.reseptinmuokkausnakyma();
    }
    
    public void reseptinmuokkausnakyma(){
        this.otsikkoMuokkaus();
        this.raakaAineMuokkaus();
        this.valmistusvaiheMuokkaus();
        SwingUtilities.updateComponentTreeUI(this);
        this.ikkuna.getVerticalScrollBar().setValue(0);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                if (Reseptikortisto.tallennustila() == false) {
                    tallennuskysely.setVisible(true);
                } else {
                    dispose();
                }

            }
        });
    }

    public void otsikkoSelailu() {
        this.otsikko.removeAll();
        this.otsikko.setLayout(new BorderLayout());
        this.otsikko.setBackground(Paanakyma.taustavari);
        this.otsikkoYla = new JPanel();
        this.otsikkoYla.setLayout(new FlowLayout());
        this.otsikkoYla.setBackground(Paanakyma.taustavari);
        this.nimi = new JLabel(this.resepti.getNimi());
        this.nimi.setFont(this.otsikkoTeksti);
        this.otsikkoYla.add(this.nimi);
        this.muokkaaNappi = new JButton("muokkaa reseptiä");
        this.otsikkoYla.add(this.muokkaaNappi);
        this.muokkaaNappi.addActionListener(e -> this.muokkaaReseptia());
        this.otsikko.add(this.otsikkoYla, BorderLayout.NORTH);
        //this.otsikko.repaint();
        this.otsikkoAla = new JPanel();
        this.otsikkoAla.setLayout(new FlowLayout());
        this.otsikkoAla.setBackground(Paanakyma.taustavari);
        this.kuvailu = new JTextArea();
        this.kuvailu.setFont(this.leipateksti);
        this.kuvailu.setSize(700, 50);
        this.kuvailu.setBackground(Paanakyma.taustavari);
        this.kuvailu.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        this.kuvailu.setLineWrap(true);
        this.kuvailu.setWrapStyleWord(true);        
        kuvailu.setEditable(false);
        kuvailu.setText(resepti.getKuvailu());
        this.otsikkoAla.add(this.kuvailu);
        this.otsikko.add(this.otsikkoAla, BorderLayout.SOUTH);
    }

    public void raakaAineSelailu() {
        //Luodaan raaka-ainenäkymä
        this.raakaAinePaneeli.removeAll();
        this.raakaAinePaneeli.setLayout(new BorderLayout());
        this.raakaAinePaneeli.setBackground(Paanakyma.taustavari);

        //Luodaan raaka-aineiden otsikko 
        this.raakaAineetYla = new JPanel();
        this.raakaAineetYla.setLayout(new FlowLayout());
        this.raakaAineetYla.setBackground(Paanakyma.taustavari);
        this.rAineet = new JLabel("Raaka-aineet:");
        this.rAineet.setFont(this.otsikkoTeksti);
        this.raakaAineetYla.add(this.rAineet);
        this.raakaAinePaneeli.add(this.raakaAineetYla, BorderLayout.NORTH);

        //Luodaan lista raaka-aineisa
        this.raakaAineetAla = new JPanel();
        this.raakaAineetAla.setLayout(new GridLayout(this.resepti.getRaakaAineet().size(), 1));
        this.raakaAineetAla.setBackground(Paanakyma.taustavari);

        for (RaakaAine aine : this.resepti.getRaakaAineet()) {
            //Luodaan kukin raaka-aine erikseen
            this.yksiRAine = new JPanel();
            this.yksiRAine.setLayout(new FlowLayout());
            this.yksiRAine.setBackground(Paanakyma.taustavari);
            this.raakaAine = aine;
            this.maara = new JLabel(raakaAine.getMaara());
            this.maara.setFont(leipateksti);
            this.mitta = new JLabel(raakaAine.getMitta());
            this.mitta.setFont(leipateksti);
            this.rAine = new JLabel(raakaAine.getNimi());
            this.rAine.setFont(leipateksti);
            this.yksiRAine.add(this.maara);
            this.yksiRAine.add(this.mitta);
            this.yksiRAine.add(this.rAine);
            this.raakaAineetAla.add(this.yksiRAine);
        }
        this.raakaAinePaneeli.add(this.raakaAineetAla, BorderLayout.SOUTH);
    }

    public void valmistusvaiheSelailu() {
        //Luodaan valmistusvaihenäkymä
        this.tausta.setBackground(Paanakyma.taustavari);
        this.valmVaihePaneeli.removeAll();
        this.valmVaihePaneeli.setLayout(new BorderLayout());
        this.valmVaihePaneeli.setBackground(Paanakyma.taustavari);

        //Luodaan valmistusvaiheille otsikko
        this.valmistusvaiheetYla = new JPanel();
        this.valmistusvaiheetYla.setLayout(new FlowLayout());
        this.valmistusvaiheetYla.setBackground(Paanakyma.taustavari);
        this.vVaiheet = new JLabel("Valmistusvaiheet:");
        this.vVaiheet.setFont(this.otsikkoTeksti);
        this.valmistusvaiheetYla.add(this.vVaiheet);
        this.valmVaihePaneeli.add(this.valmistusvaiheetYla, BorderLayout.NORTH);

        //Luodaan lista valmistusvaiheista
        this.valmistusvaiheetAla = new JPanel();
        this.valmistusvaiheetAla.setLayout(new GridLayout(this.resepti.getVaiheet().size(), 1));
        this.valmistusvaiheetAla.setBackground(Paanakyma.taustavari);

        for (String uusiVaihe : this.resepti.getVaiheet()) {
            //Luodaan kukin valmistusvaihe erikseen ja asetetaan omaan paneeliinsa
            this.yksivaihe = new JPanel();
            this.yksivaihe.setLayout(new FlowLayout());
            this.yksivaihe.setBackground(Paanakyma.taustavari);
            this.vaihe = new JTextArea();
            this.vaihe.setFont(this.leipateksti);
            this.vaihe.setSize(700, 50);
            this.vaihe.setBackground(Paanakyma.taustavari);
            this.vaihe.setBorder(javax.swing.BorderFactory.createEmptyBorder());
            this.vaihe.setLineWrap(true);
            this.vaihe.setWrapStyleWord(true);
            this.vaihe.setEditable(false);
            this.vaihe.setText(uusiVaihe);
            this.yksivaihe.add(this.vaihe);
            this.valmistusvaiheetAla.add(this.yksivaihe);
        }
        this.valmVaihePaneeli.add(this.valmistusvaiheetAla, BorderLayout.SOUTH);
    }

    public void otsikkoMuokkaus() {
        this.otsikko.removeAll();
        this.otsikko.setLayout(new BorderLayout());
        this.otsikkoYla = new JPanel();
        this.otsikkoYla.setLayout(new FlowLayout());
        this.nimiMuokkaus = new JTextField(Resepti.NIMI_PITUUS);
        this.nimiMuokkaus.setDocument(new JTextFieldLimit(Resepti.NIMI_PITUUS));
        this.nimiMuokkaus.setText(this.muokattavaResepti.getNimi());
        this.otsikkoYla.add(this.nimiMuokkaus);
        this.nimiMuokkaus.getDocument().addDocumentListener(new PaivitaNimi(this.nimiMuokkaus, this.muokattavaResepti));
        this.poista = new JButton("Poista resepti");
        this.otsikkoYla.add(this.poista);
        this.poista.addActionListener(e -> this.reseptinPoistoKysely.setVisible(true));
        this.tallenna = new JButton("Tallenna resepti");
        this.otsikkoYla.add(this.tallenna);
        this.tallenna.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                if (muokattavaResepti.getNimi().trim().isEmpty())
                    JOptionPane.showMessageDialog(null, "Reseptillä täytyy olla nimi!");
                else {
                    muokattavaResepti.puhdistaResepti();
        resepti.kopioi(muokattavaResepti);
        rKortisto.tallenna();
        reseptiselailu();
                }
            }
    });
        
        this.otsikko.add(this.otsikkoYla, BorderLayout.NORTH);
        this.otsikko.repaint();
        this.otsikkoAla = new JPanel();
        this.otsikkoAla.setLayout(new FlowLayout());
        this.kuvailu = new JTextArea();
        this.kuvailu.setFont(this.leipateksti);
        this.kuvailu.setSize(700, 50);
        this.kuvailu.setLineWrap(true);
        this.kuvailu.setWrapStyleWord(true);
        this.kuvailu.setDocument(new JTextFieldLimit(Resepti.KUVAILU_PITUUS));
        this.kuvailu.setEditable(true);        
        this.kuvailu.setText(muokattavaResepti.getKuvailu());
        this.otsikkoAla.add(this.kuvailu);
        this.kuvailu.getDocument().addDocumentListener(new PaivitaKuvailu(this.kuvailu, this.muokattavaResepti));
        
        this.otsikko.add(this.otsikkoAla, BorderLayout.SOUTH);
    }

    public void raakaAineMuokkaus() {
        //Luodaan raaka-aineiden muokkausnäkymä
        this.raakaAinePaneeli.removeAll();
        this.raakaAinePaneeli.setLayout(new BorderLayout());

        //Luodaan raaka-aineiden otsikko 
        this.raakaAineetYla = new JPanel();
        this.raakaAineetYla.setLayout(new FlowLayout());
        this.rAineet = new JLabel("Raaka-aineet:");
        this.rAineet.setFont(this.otsikkoTeksti);
        this.raakaAineetYla.add(this.rAineet);
        this.lisaaRaakaAine = new JButton("Lisää raaka-aine");
        this.raakaAineetYla.add(this.lisaaRaakaAine);
        this.lisaaRaakaAine.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                muokattavaResepti.lisaaRaakaAine(new RaakaAine());
                Reseptikortisto.tallentamatonMuutos();
                reseptinmuokkausnakyma();
                }
            });
        this.raakaAinePaneeli.add(this.raakaAineetYla, BorderLayout.NORTH);

        //Luodaan raaka-ainelistalle otsikot
        this.raakaAineetAla = new JPanel();
        this.raakaAineetAla.setLayout(new GridLayout(this.muokattavaResepti.getRaakaAineet().size()+1, 1));
        this.yksiRAine = new JPanel();
            this.yksiRAine.setLayout(new FlowLayout());
            this.rAineMaaraMuokkaus = new JTextField("Määrä", RaakaAine.MAARA_PITUUS);
            this.rAineMaaraMuokkaus.setEditable(false);
            this.rAineMaaraMuokkaus.setBackground(Color.yellow);
            this.rAineMittaMuokkaus = new JTextField("Mittayksikkö", RaakaAine.MITTA_PITUUS);
            this.rAineMittaMuokkaus.setEditable(false);
            this.rAineMittaMuokkaus.setBackground(Color.yellow);
            this.rAineNimiMuokkaus = new JTextField("Raaka-aine", RaakaAine.R_AINE_NIMI_PITUUS);
            this.rAineNimiMuokkaus.setEditable(false);
            this.rAineNimiMuokkaus.setBackground(Color.yellow);
            this.yksiRAine.add(this.rAineMaaraMuokkaus);
            this.yksiRAine.add(this.rAineMittaMuokkaus);
            this.yksiRAine.add(this.rAineNimiMuokkaus);
            this.raakaAineetAla.add(this.yksiRAine);
            
            //Luodaan lista raaka-aineista
        for (RaakaAine aine : this.muokattavaResepti.getRaakaAineet()) {
            //Luodaan kukin raaka-aine erikseen
            this.yksiRAine = new JPanel();
            this.yksiRAine.setLayout(new FlowLayout());
            this.raakaAine = aine;
            this.rAineMaaraMuokkaus = new JTextField(RaakaAine.MAARA_PITUUS);
            this.rAineMaaraMuokkaus.setDocument(new JTextFieldLimit(RaakaAine.MAARA_PITUUS));
            this.rAineMaaraMuokkaus.setText(this.raakaAine.getMaara());
            this.rAineMaaraMuokkaus.getDocument().addDocumentListener(new PaivitaRaakaAineMaara(this.rAineMaaraMuokkaus, this.raakaAine));
            this.rAineMittaMuokkaus = new JTextField(this.raakaAine.getMitta(), RaakaAine.MITTA_PITUUS);
            this.rAineMittaMuokkaus.setDocument(new JTextFieldLimit(RaakaAine.MITTA_PITUUS));
            this.rAineMittaMuokkaus.setText(this.raakaAine.getMitta());
            this.rAineMittaMuokkaus.getDocument().addDocumentListener(new PaivitaRaakaAineMitta(this.rAineMittaMuokkaus, this.raakaAine));
            this.rAineNimiMuokkaus = new JTextField(RaakaAine.R_AINE_NIMI_PITUUS);
            this.rAineNimiMuokkaus.setDocument(new JTextFieldLimit(RaakaAine.R_AINE_NIMI_PITUUS));
            this.rAineNimiMuokkaus.setText(this.raakaAine.getNimi());
            this.rAineNimiMuokkaus.getDocument().addDocumentListener(new PaivitaRaakaAineNimi(this.rAineNimiMuokkaus, this.raakaAine));
            this.yksiRAine.add(this.rAineMaaraMuokkaus);
            this.yksiRAine.add(this.rAineMittaMuokkaus);
            this.yksiRAine.add(this.rAineNimiMuokkaus);
            this.raakaAineetAla.add(this.yksiRAine);
        }
        this.raakaAinePaneeli.add(this.raakaAineetAla, BorderLayout.SOUTH);
    }

    public void valmistusvaiheMuokkaus() {
        //Luodaan valmistusvaiheiden muokkausnäkymä
        this.valmVaihePaneeli.removeAll();
        this.valmVaihePaneeli.setLayout(new BorderLayout());

        //Luodaan valmistusvaiheille otsikko
        this.valmistusvaiheetYla = new JPanel();
        this.valmistusvaiheetYla.setLayout(new FlowLayout());
        this.vVaiheet = new JLabel("Valmistusvaiheet:");
        this.vVaiheet.setFont(this.otsikkoTeksti);
        this.valmistusvaiheetYla.add(this.vVaiheet);
        this.lisaaValmistusvaihe = new JButton("Lisää valmistusvaihe");
        this.valmistusvaiheetYla.add(this.lisaaValmistusvaihe);
        this.lisaaValmistusvaihe.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
                muokattavaResepti.lisaaVaihe("");
                Reseptikortisto.tallentamatonMuutos();
                reseptinmuokkausnakyma();
                }
            });
        this.valmVaihePaneeli.add(this.valmistusvaiheetYla, BorderLayout.NORTH);

        //Luodaan lista valmistusvaiheista
        this.valmistusvaiheetAla = new JPanel();
        this.valmistusvaiheetAla.setLayout(new GridLayout(this.muokattavaResepti.getVaiheet().size(), 1));

        for (int i = 0; i < this.muokattavaResepti.getVaiheet().size(); i++) {
            //Luodaan kukin valmistusvaihe erikseen ja asetetaan omaan paneeliinsa
            this.yksivaihe = new JPanel();
            this.yksivaihe.setLayout(new FlowLayout());
            this.vaihe = new JTextArea();
            this.vaihe.setFont(this.leipateksti);
            this.vaihe.setSize(700, 50);
            this.vaihe.setLineWrap(true);
            this.vaihe.setWrapStyleWord(true);
            this.vaihe.setDocument(new JTextFieldLimit(Resepti.VAIHE_PITUUS));
            this.vaihe.setEditable(true);
            this.vaihe.setText(this.muokattavaResepti.getVaihe(i));
            this.yksivaihe.add(this.vaihe);
            this.vaihe.getDocument().addDocumentListener(new PaivitaValmistusvaihe(this.vaihe, this.muokattavaResepti, i));
            this.valmistusvaiheetAla.add(this.yksivaihe);
        }
        this.valmVaihePaneeli.add(this.valmistusvaiheetAla, BorderLayout.SOUTH);
    }

}
